/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.elzakaria.kafkaproducer.avro;
@org.apache.avro.specific.AvroGenerated
public enum UserEventType implements org.apache.avro.generic.GenericEnumSymbol<UserEventType> {
  CREATED, UPDATED, DELETED, LOGIN, LOGOUT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserEventType\",\"namespace\":\"com.elzakaria.kafkaproducer.avro\",\"symbols\":[\"CREATED\",\"UPDATED\",\"DELETED\",\"LOGIN\",\"LOGOUT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
